# Generated by Django 6.0.1 on 2026-02-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0021_result_grade_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Academics.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('TERM 1', 'Term 1'), ('TERM 2', 'Term 2'), ('TERM 3', 'Term 3')], max_length=20)),
                ('academic_year', models.IntegerField(default=2026)),
                ('tuition_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('target_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='Academics.classlevel')),
            ],
            options={
                'unique_together': {('target_class', 'term', 'academic_year')},
            },
        ),
    ]
