# Generated by Django 6.0.1 on 2026-02-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_role_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('DAY', 'Day'), ('BOARDING', 'Boarding')], default='DAY', help_text='Required to determine the correct fee structure', max_length=10),
        ),
    ]
