# Generated by Django 6.0.1 on 2026-02-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_studentprofile_student_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_type',
        ),
    ]
