# Generated by Django 6.0.1 on 2026-02-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_studentprofile_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('DAY', 'Day Student'), ('BOARDING', 'Boarding Student')], default='DAY', max_length=10),
        ),
    ]
