# Generated by Django 6.0.1 on 2026-02-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_courseassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
