# Generated by Django 4.2.7 on 2026-02-02 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Academics', '0004_alter_classlevel_id_alter_courseassignment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='timetables/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='Academics.classlevel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
