# Generated by Django 6.0.1 on 2026-02-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0006_alter_classlevel_id_alter_courseassignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('assignment', 'Assignment')], max_length=10),
        ),
    ]
