# Generated by Django 6.0.1 on 2026-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0007_alter_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
