# Generated by Django 6.0.1 on 2026-02-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0009_result'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='class_levels',
            field=models.ManyToManyField(related_name='course_assignments', to='Academics.classlevel'),
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='class_level',
        ),
    ]
