# Generated by Django 6.0.1 on 2026-02-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0010_alter_courseassignment_unique_together_and_more'),
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='class_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_materials', to='Academics.classlevel'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('assignment', 'Assignment'), ('test', 'Test/Quiz')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('teacher', 'subject', 'academic_session')},
        ),
    ]
