# Generated by Django 6.0.1 on 2026-02-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0011_material_class_level_alter_material_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_materials', to='Academics.classlevel'),
            preserve_default=False,
        ),
    ]
