# Generated by Django 6.0.1 on 2026-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0012_alter_material_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='class_level',
        ),
        migrations.AddField(
            model_name='material',
            name='target_classes',
            field=models.ManyToManyField(related_name='class_materials', to='Academics.classlevel'),
        ),
    ]
