# Generated by Django 6.0.1 on 2026-02-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0016_alter_studymaterial_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('DAY', 'Day Student'), ('BOARDING', 'Boarding Student')], default='DAY', max_length=10),
        ),
    ]
