# Generated by Django 6.0.1 on 2026-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0018_subjectresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectresource',
            name='subject',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('assignment', 'Assignment'), ('test', 'Test/Quiz')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='class_materials', to='Academics.classlevel'),
        ),
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
        migrations.DeleteModel(
            name='SubjectResource',
        ),
    ]
